microsoft/vscode-docker-extensibility

packages/vscode-docker-registries-extension/package.json
packages/vscode-docker-registries-extension/src/clients/Azure/AzureRegistryDataProvider.ts
packages/vscode-docker-registries-extension/src/extension.ts
packages/vscode-docker-registries/src/clients/DockerHub/DockerHubRegistryDataProvider.ts
packages/vscode-docker-registries/src/clients/RegistryV2/registryV2Request.ts

- Fixed a typo in DockerHub context values
- Fixed Invalid json response body Error

Fixed Invalid json response body Error 

---

package-lock.json
packages/vscode-docker-registries-extension/src/clients/GitLab/GitLabRegistryDataProvider.ts
packages/vscode-docker-registries/package.json
packages/vscode-docker-registries/src/clients/Common/CommonRegistryDataProvider.ts
packages/vscode-docker-registries/src/clients/Common/models.ts
packages/vscode-docker-registries/src/clients/RegistryV2/RegistryV2DataProvider.ts
packages/vscode-docker-registries/src/clients/RegistryV2/registryV2Request.ts

What's done:
TODO: 
Related to https://github.com/microsoft/vscode-docker/pull/4026

Add Time CreatedLogic for Registries

---

packages/vscode-docker-registries/src/clients/DockerHub/DockerHubRegistryDataProvider.ts
packages/vscode-docker-registries/src/clients/GitHub/GitHubRegistryDataProvider.ts

Related to https://github.com/microsoft/vscode-docker/pull/4046

Cleanup Registries Implementation

---

packages/vscode-docker-registries/src/wizard/showInputBox.ts

Addresses https://github.com/microsoft/vscode-docker-extensibility/pull/187#discussion_r1319044204

Simplified showInputBox() implementation

---

packages/vscode-docker-registries/src/clients/GenericRegistryV2/GenericRegistryV2DataProvider.ts

Closes #193 
Commit that did the todo: https://github.com/microsoft/vscode-docker/pull/4026/commits/7b831f42516a1a415a51c93df289daf67d421f47

Remove TODO in GenericV2Provider

---

package-lock.json
packages/vscode-docker-registries/package.json
packages/vscode-docker-registries/src/clients/GenericRegistryV2/GenericRegistryV2DataProvider.ts
packages/vscode-docker-registries/src/clients/GenericRegistryV2/GenericRegistryV2WizardPromptStep.ts
packages/vscode-docker-registries/src/clients/RegistryV2/registryV2Request.ts
packages/vscode-docker-registries/src/utils/errors.ts
packages/vscode-docker-registries/src/utils/httpRequest.ts

Closes https://github.com/microsoft/vscode-docker/issues/4091
Closes https://github.com/microsoft/vscode-docker/issues/4092

Check if Registry already exists for Generic V2 Registries & Added Better Error Handling Logic

---

package-lock.json
packages/vscode-docker-registries/package.json
packages/vscode-docker-registries/src/clients/DockerHub/DockerHubRegistryDataProvider.ts
packages/vscode-docker-registries/src/clients/GitHub/GitHubRegistryDataProvider.ts
packages/vscode-docker-registries/src/wizard/RegistryWizardPromptStep.ts
packages/vscode-docker-registries/src/wizard/showInputBox.ts

Stop User from Going Pass Step unless input validates

---

package-lock.json
packages/vscode-container-client/package.json
packages/vscode-container-client/src/clients/DockerClientBase/DockerClientBase.ts
packages/vscode-container-client/src/clients/DockerClientBase/parsePruneLikeOutput.ts

Parse `docker prune` Output

---

package-lock.json
packages/vscode-docker-registries/package.json
packages/vscode-docker-registries/src/auth/BasicAuthProvider.ts

Related to https://github.com/microsoft/vscode-docker/issues/4117

Registries - Allow Empty Username During Auth 

---

packages/vscode-docker-registries/src/clients/DockerHub/DockerHubRegistryDataProvider.ts

Related to https://github.com/microsoft/vscode-docker/issues/4120

Added Scope definition to DockerHub Secret Step

---

packages/vscode-container-client/src/clients/DockerClientBase/DockerClientBase.ts
packages/vscode-container-client/src/clients/DockerClientBase/parsePruneLikeOutput.ts
packages/vscode-container-client/src/test/DockerClient.test.ts

Fix prune parsing logic and add tests for it

---

packages/vscode-container-client/README.md
packages/vscode-docker-registries/README.md

Updates to readmes

---

package-lock.json
packages/vscode-docker-registries/package.json
packages/vscode-docker-registries/src/clients/GitHub/GitHubRegistryDataProvider.ts
packages/vscode-docker-registries/src/clients/RegistryV2/RegistryV2DataProvider.ts

Needed for https://github.com/microsoft/vscode-docker/issues/3996

Expose method to get image manifest

---

package-lock.json
packages/vscode-docker-registries/package.json
packages/vscode-docker-registries/src/clients/GenericRegistryV2/GenericRegistryV2DataProvider.ts

Needed for https://github.com/microsoft/vscode-docker/issues/4182

Throw registry URL to lowercase

---

.vscode/settings.json
package-lock.json
packages/vscode-docker-registries/CHANGELOG.md
packages/vscode-docker-registries/package.json
packages/vscode-docker-registries/src/clients/DockerHub/DockerHubRegistryDataProvider.ts

Fixes #219. I verified by testing with a page size of 1.

Fix Docker Hub paging and increase page size to 100

---

packages/vscode-container-client/src/clients/DockerClientBase/DockerClientBase.ts
packages/vscode-container-client/src/clients/DockerClientBase/parseListFilesCommandOutput.ts

Update stat calls to account for .* possibly not matching implicit . and .. folder paths

---

packages/vscode-docker-registries/src/clients/GitHub/GitHubRegistryDataProvider.ts

In GHCR, throw org names and repository names to lowercase

---

package-lock.json
packages/vscode-docker-registries/CHANGELOG.md
packages/vscode-docker-registries/package.json
packages/vscode-docker-registries/src/clients/GitHub/GitHubRegistryDataProvider.ts
packages/vscode-docker-registries/src/clients/RegistryV2/RegistryV2DataProvider.ts
packages/vscode-docker-registries/src/clients/RegistryV2/registryV2Request.ts

Eliminate query parameter from `RegistryV2RequestOptions`

---

.azure-pipelines/release-npm.yml

Dry run: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=11150142&view=results
See also: https://github.com/microsoft/compose-language-service/pull/163

Update to use modernized NPM release pipeline

---

package-lock.json
packages/vscode-container-client/CHANGELOG.md
packages/vscode-container-client/package.json
packages/vscode-container-client/src/clients/DockerClientBase/DockerClientBase.ts
packages/vscode-container-client/src/contracts/ContainerClient.ts

Implement `statsContainers` command

---

.vscode/launch.json
package-lock.json
packages/vscode-container-client/CHANGELOG.md
packages/vscode-container-client/package.json
packages/vscode-processutils/CHANGELOG.md
packages/vscode-processutils/package.json
packages/vscode-processutils/src/test/spawnStreamAsync.test.ts
packages/vscode-processutils/src/utils/Shell.ts
packages/vscode-processutils/src/utils/commandLineBuilder.ts
packages/vscode-processutils/src/utils/spawnStreamAsync.ts

Fix a handful of issues with `spawnStreamAsync`

---

package-lock.json
packages/vscode-processutils/CHANGELOG.md
packages/vscode-processutils/package.json
packages/vscode-processutils/src/utils/getSafeExecPath.ts
packages/vscode-processutils/src/utils/spawnStreamAsync.ts

This will be needed by the AZD extension.

Allow passing in an alternate PATH variable
